name: Assemble Scala source

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build-server:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'sbt'
    - name: Setup sbt installer
      uses: sbt/setup-sbt@v1.1.5
    - name: Assemble Scala 2.13 source
      run: sbt -v server/assembly
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.1
      with:
        name: 'build-${{ github.sha }}'
        path: 'server/target/scala-2.13/formulon-*.jar'
        if-no-files-found: error
    - name: Sbt Dependency Submission
      uses: scalacenter/sbt-dependency-submission@v3.1.0
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'sbt'
    - name: Setup sbt installer
      uses: sbt/setup-sbt@v1.1.5
    - name: Run unit tests
      run: sbt test
